#ifndef ENGINE_CONSTANTS_GLSL
#define ENGINE_CONSTANTS_GLSL

#define AS_MAX_GLOBAL_CUSTOM_PARAMS 8

/*Mains*/
#define AS_BINDING_GLOBAL_UBO 0
#define AS_BINDING_VIEWPORT_UBO 1

/*GUI*/
#define AS_BINDING_GUI_TEXTURE 300
#endif