#ifndef ENGINE_CONSTANTS_GLSL
#define ENGINE_CONSTANTS_GLSL

#define AS_MAX_GLOBAL_CUSTOM_PARAMS 8

/*Mains*/
#define AS_BINDING_GLOBAL_UBO 0
#define AS_BINDING_VIEWPORT_UBO 1

/*Texture Pool*/
#define AS_MAX_POOLED_TEXTURES 1024
#define AS_BINDING_TEXTURE_POOL 200
#define AS_DESCSET_TEXTURE_POOL 0

/*GUI*/
#define AS_BINDING_GUI_TEXTURE 300
#endif